package wildlifeassignment;

import java.util.*;
import java.awt.*;
import javax.swing.*;

public final class MainMenu extends javax.swing.JFrame {
    public static int selectedIndex = 0;
    public static MainMenu main = new MainMenu();

    public MainMenu() {
        
        initComponents();
        BWA.NewData();
        PopulateWatchList();
        PopulateObserverList();     
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        listWatchList = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        btnAddAnimal = new javax.swing.JButton();
        btnRemoveAnimal = new javax.swing.JButton();
        btnEditAnimal = new javax.swing.JButton();
        btnAddObservation = new javax.swing.JButton();
        btnViewObservations = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstWatchListThreat = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstWatchListName = new javax.swing.JList();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listObserver = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnCall = new javax.swing.JButton();
        btnViewObserver = new javax.swing.JButton();
        btnAddObserver = new javax.swing.JButton();
        btnContract = new javax.swing.JButton();
        jSplitPane4 = new javax.swing.JSplitPane();
        jSplitPane5 = new javax.swing.JSplitPane();
        jSplitPane6 = new javax.swing.JSplitPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstPhoneNo = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstEmail = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstAddress = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstObserverName = new javax.swing.JList();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 153));

        jScrollPane3.setViewportView(listWatchList);

        jSplitPane1.setRightComponent(jScrollPane3);

        btnAddAnimal.setText("Add Animal");
        btnAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnimalActionPerformed(evt);
            }
        });

        btnRemoveAnimal.setText("Remove Animal");
        btnRemoveAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAnimalActionPerformed(evt);
            }
        });

        btnEditAnimal.setText("Edit Animal Threat Level");
        btnEditAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAnimalActionPerformed(evt);
            }
        });

        btnAddObservation.setText("New Observation");
        btnAddObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddObservationActionPerformed(evt);
            }
        });

        btnViewObservations.setText("View Recent Observations");
        btnViewObservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewObservationsActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewObservations, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btnEditAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddObservation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnEditAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddObservation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        jSplitPane1.setLeftComponent(jPanel4);

        jSplitPane2.setDividerLocation(250);
        jSplitPane2.setDividerSize(0);

        lstWatchListThreat.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstWatchListThreat.setFocusable(false);
        lstWatchListThreat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstThreatLevelClicked(evt);
            }
        });
        jScrollPane5.setViewportView(lstWatchListThreat);

        jSplitPane2.setRightComponent(jScrollPane5);

        lstWatchListName.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstWatchListName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstWatchListNameClicked(evt);
            }
        });
        jScrollPane6.setViewportView(lstWatchListName);

        jSplitPane2.setLeftComponent(jScrollPane6);

        jSplitPane1.setRightComponent(jSplitPane2);

        jTabbedPane1.addTab("Animal Watch List", jSplitPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSplitPane3.setRightComponent(jPanel1);

        jScrollPane1.setViewportView(listObserver);

        jSplitPane3.setRightComponent(jScrollPane1);

        btnCall.setText("Issue Call");
        btnCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallActionPerformed(evt);
            }
        });

        btnViewObserver.setText("View Observer");
        btnViewObserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewObserverActionPerformed(evt);
            }
        });

        btnAddObserver.setText("Add Observer");
        btnAddObserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddObserverActionPerformed(evt);
            }
        });

        btnContract.setText("Issue Contract");
        btnContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContractActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnContract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddObserver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewObserver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCall, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddObserver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewObserver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCall, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnContract, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane3.setLeftComponent(jPanel5);

        jSplitPane4.setDividerLocation(170);
        jSplitPane4.setDividerSize(0);

        jSplitPane5.setDividerLocation(250);
        jSplitPane5.setDividerSize(0);

        jSplitPane6.setDividerLocation(100);
        jSplitPane6.setDividerSize(0);

        lstPhoneNo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPhoneNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPhoneNoMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(lstPhoneNo);

        jSplitPane6.setLeftComponent(jScrollPane7);

        lstEmail.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEmailMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(lstEmail);

        jSplitPane6.setRightComponent(jScrollPane8);

        jSplitPane5.setRightComponent(jSplitPane6);

        lstAddress.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAddressMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(lstAddress);

        jSplitPane5.setLeftComponent(jScrollPane4);

        jSplitPane4.setRightComponent(jSplitPane5);

        lstObserverName.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstObserverName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstObserverNameClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstObserverName);

        jSplitPane4.setLeftComponent(jScrollPane2);

        jSplitPane3.setRightComponent(jSplitPane4);

        jTabbedPane1.addTab("Observers", jSplitPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAddObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddObservationActionPerformed
        if (lstWatchListName.getSelectedIndex() < 1) {
            Utilities.InfoBox("Please select an animal from the list.", "New Observation");
        }
        else {
            selectedIndex = lstWatchListName.getSelectedIndex()-1;            
            NewObservation newObservation = new NewObservation();
            newObservation.setVisible(true);
        }
    }//GEN-LAST:event_btnAddObservationActionPerformed

    private void btnAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnimalActionPerformed
        AddAnimal newAddAnimal = new AddAnimal();
        newAddAnimal.setVisible(true);
    }//GEN-LAST:event_btnAddAnimalActionPerformed

    public void PopulateWatchList() {
        ArrayList<String> listName = new ArrayList<>();
        ArrayList<String> listThreat = new ArrayList<>();
        
        listName.add("Common animal name");
        listThreat.add("Threat Level");
        
        Utilities.SortLists();
        
        for (Animal a : BWA.watchList) {
            listName.add(a.getName());
            listThreat.add(Integer.toString(a.getThreatLevel()));
        }
            lstWatchListName.setListData(listName.toArray());
            lstWatchListThreat.setListData(listThreat.toArray());
    }
    
    public void PopulateObserverList() {
        ArrayList<String> listName = new ArrayList<>();
        ArrayList<String> listAddress = new ArrayList<>();
        ArrayList<String> listPhoneNo = new ArrayList<>();
        ArrayList<String> listEmail = new ArrayList<>();
                
        listName.add("Observer Name");
        listAddress.add("Address");
        listPhoneNo.add("Phone Number");
        listEmail.add("Email Address");
        
        Utilities.SortLists();
        
        for (Observer x : BWA.observers) {
            listName.add(x.getName());
            listAddress.add(x.getAddress());
            listPhoneNo.add(x.getPhoneNo());
            listEmail.add(x.getEmail());
        }
        
        lstObserverName.setListData(listName.toArray());
        lstAddress.setListData(listAddress.toArray());
        lstPhoneNo.setListData(listPhoneNo.toArray());
        lstEmail.setListData(listEmail.toArray());
    }
    
    private void btnRemoveAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAnimalActionPerformed
        if (lstWatchListName.getSelectedIndex() < 1) {
            Utilities.InfoBox("Please select an animal from the list.", "Remove Animal");
        }
        else {
            if (JOptionPane.showConfirmDialog(null, "Are you sure you wish to remove the animal from the watch list?", "Request", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)
                    == JOptionPane.YES_OPTION) {
                int index = lstWatchListName.getSelectedIndex();
                BWA.watchList.remove(index-1);
                PopulateWatchList();
            }
            else {}                
        }
    }//GEN-LAST:event_btnRemoveAnimalActionPerformed

    private int IndexFix(int x) {
        if (x == 0) {
            x = 1;
        }
        return x;
    }
    
    private void AnimalIndex(int index) {
        int newIndex;
        
        newIndex = IndexFix(index);
        SetAnimalIndex(newIndex);
    }
    
    private void SetAnimalIndex(int index) {
        lstWatchListName.setSelectedIndex(index);
        lstWatchListThreat.setSelectedIndex(index);
    }
    
    private void ObserverIndex(int index) {
        int newIndex;
        
        newIndex = IndexFix(index);
        SetObserverIndex(newIndex);
    }
    
    private void SetObserverIndex(int index) {
        lstObserverName.setSelectedIndex(index);
        lstAddress.setSelectedIndex(index);
        lstPhoneNo.setSelectedIndex(index);
        lstEmail.setSelectedIndex(index);
    }
    
    
    private void lstWatchListNameClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstWatchListNameClicked
        AnimalIndex(lstWatchListName.getSelectedIndex());
    }//GEN-LAST:event_lstWatchListNameClicked

    private void lstThreatLevelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstThreatLevelClicked
        AnimalIndex(lstWatchListThreat.getSelectedIndex());
    }//GEN-LAST:event_lstThreatLevelClicked

    private void btnEditAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAnimalActionPerformed
        selectedIndex = lstWatchListName.getSelectedIndex()-1;
        String[] threatLevels = {"1", "2", "3", "4", "5" };
        JFrame frame = new JFrame("Threat Level");
        
        if (selectedIndex < 0) {
            Utilities.InfoBox("Please select an animal from the list.", "Remove Animal");
        }
        else {
            try {
            int input = Integer.parseInt((String) JOptionPane.showInputDialog(frame, "Please enter new threat level", "Threat Level",
                    JOptionPane.QUESTION_MESSAGE, null, threatLevels, threatLevels[0])); //combo box must have corect value           
                int index = selectedIndex;
                Animal x = BWA.watchList.get(index);
                x.setThreatLevel(input);
                Utilities.InfoBox("Threat level updated", "Threat level update");
                PopulateWatchList(); //refresh list
                SetAnimalIndex(selectedIndex +1); //set old index
            }
            catch (HeadlessException | NumberFormatException e) {} 
        }
    }//GEN-LAST:event_btnEditAnimalActionPerformed

    private void lstObserverNameClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstObserverNameClicked
        ObserverIndex(lstObserverName.getSelectedIndex());
    }//GEN-LAST:event_lstObserverNameClicked

    private void lstAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAddressMouseClicked
        ObserverIndex(lstAddress.getSelectedIndex());
    }//GEN-LAST:event_lstAddressMouseClicked

    private void lstPhoneNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPhoneNoMouseClicked
        ObserverIndex(lstPhoneNo.getSelectedIndex());
    }//GEN-LAST:event_lstPhoneNoMouseClicked

    private void lstEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEmailMouseClicked
        ObserverIndex(lstEmail.getSelectedIndex());
    }//GEN-LAST:event_lstEmailMouseClicked

    private void btnViewObservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewObservationsActionPerformed
        RecentObservation newObservation = new RecentObservation();
        newObservation.setVisible(true);
    }//GEN-LAST:event_btnViewObservationsActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddObserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddObserverActionPerformed
        NewObserver newObserver = new NewObserver();
        newObserver.setVisible(true);
    }//GEN-LAST:event_btnAddObserverActionPerformed

    private void btnViewObserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewObserverActionPerformed
        selectedIndex = lstObserverName.getSelectedIndex() -1;
        if (selectedIndex < 0) {        
            Utilities.InfoBox("Please selected an observer from the list", "View observer");
        }
        else {
            ViewObserver viewObserver = new ViewObserver();
            viewObserver.setVisible(true);
        }
    }//GEN-LAST:event_btnViewObserverActionPerformed

    private void btnCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallActionPerformed
        selectedIndex = lstObserverName.getSelectedIndex()-1;
        if (selectedIndex < 0) {
            Utilities.InfoBox("Please selected an observer from the list", "New call");
        }
        else {
            NewCall newCall = new NewCall();
            newCall.setVisible(true);
        }
    }//GEN-LAST:event_btnCallActionPerformed

    private void btnContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContractActionPerformed
        selectedIndex = lstObserverName.getSelectedIndex()-1;
        if (selectedIndex < 0) {
            Utilities.InfoBox("Please selected an observer from the list", "New call");
        }
        else if (BWA.observers.get(selectedIndex) instanceof ProfessionalOb) {
            Utilities.InfoBox("Observer must not already have a contract", "New Contract");
        }
        else {
            NewContract newContract = new NewContract();
            newContract.setVisible(true);
        }
    }//GEN-LAST:event_btnContractActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnimal;
    private javax.swing.JButton btnAddObservation;
    private javax.swing.JButton btnAddObserver;
    private javax.swing.JButton btnCall;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnContract;
    private javax.swing.JButton btnEditAnimal;
    private javax.swing.JButton btnRemoveAnimal;
    private javax.swing.JButton btnViewObservations;
    private javax.swing.JButton btnViewObserver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList listObserver;
    private javax.swing.JList listWatchList;
    private javax.swing.JList lstAddress;
    private javax.swing.JList lstEmail;
    private javax.swing.JList lstObserverName;
    private javax.swing.JList lstPhoneNo;
    private javax.swing.JList lstWatchListName;
    private javax.swing.JList lstWatchListThreat;
    // End of variables declaration//GEN-END:variables
}
